server:
  port: 9112
  servlet:
    context-path: /service-gateway/pix-webhook
  ssl:
    protocol: TLS
    key-store: keystore.p12
    key-store-password: Onnibank@2025
    trust-store: truststore.jks
    trust-store-password: Onnibank@2025
    trust-store-type: jks
    enabled: true
    client-auth: want

spring:
  application:
    name: "Pix Webhook Solution"
    description: "Gateway de operações de notificações de Pix"
    version: __Local__
    git-hash: __Hash__
  datasource:
    hikari:
      pool-name: pix-webhook-pool
      maximum-pool-size: ${PIX_WEBHOOK_MAX_POOL_SIZE:1}
      minimum-idle: ${PIX_WEBHOOK_MIN_POOL_SIZE:1}
      idle-timeout: 6000000
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/easysms}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:mm_core}
    password: ${POSTGRES_PASSWORD:mm_core@123}
  boot:
    admin:
      client:
        enabled: true
        url: ${SPRING_OBSERVABILITY:http://localhost:8081/service-gateway/admin-console}
        instance:
          service-base-url: ${SERVICE_BASE_URL:http://localhost:9112}
        auto-deregistration: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{logEntryId}] - %msg%n'
  level:
    com:
      onnitech: ${LOGGING_LEVEL:TRACE}
      zaxxer.hikari.HikariConfig: DEBUG

management:
  info:
    env:
      enabled: true
    git:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
    shutdown:
      enabled: true
    logfile:
      enabled: true
      external-file: logs/pix-webhook.log
    prometheus:
      enabled: true
    web:
      exposure:
        include: "*"

onnitech:
  url:
    base: ${ONNIBANK_BASE_URL:http://localhost:9108}/service-gateway/
    claim: pix-dict/callback/claim
    payment: pix-cashout/callback/payment
    payment-inbound: pix-cashin/callback/inbound
    reversal: pix-cashin/callback/reversal
    reversal-inbound: pix-cashout/callback/reversal/notification
    infraction: pix-dict/callback/infraction
    med: pix-dict/callback/med
    rco: pix-dict/callback/rco
    anti-fraud: pix-dict/callback/anti-fraud
    approval:
      payment-inbound: pix-cashin/callback/approval
      reversal-inbound: pix-cashout/callback/reversal/approval
    automatic-pix: pix-cashout/callback/automatic-pix
    automatic-pix-payment-instruction: pix-cashout/callback/automatic-pix/payment-instruction

btg:
  credentials:
    bucket-name: ${BTG_CREDENTIALS_BUCKET_NAME:onibank-cert}
    mtls-keystore-pass: ${BTG_CREDENTIALS_MTLS_KEYSTORE_PASS:password}
